---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myap-pv-claim
  labels:
    app: myap
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

