---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mynode-pv-claim
  labels:
    app: mynode
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

