apiVersion: v1
kind: Service
metadata:
  labels:
    app: myap
  name: myap
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: myap
  type: LoadBalancer
status:
  loadBalancer: {}
